; This file is automatically generated. Please don't change it manually 
	section	compressed,text 
	global rlh_RPUFOS  
rlh_RPUFOS:  
	incbin "rlh/RPUFOS.rlh"  
	global rlh_kids  
rlh_kids:  
	incbin "rlh/kids.rlh"  
	global rlh_ordi  
rlh_ordi:  
	incbin "rlh/ordi.rlh"  
	global rlh_phc25  
rlh_phc25:  
	incbin "rlh/phc25.rlh"  
	global rlh_spec1  
rlh_spec1:  
	incbin "rlh/spec1.rlh"  
	global rlh_spec2  
rlh_spec2:  
	incbin "rlh/spec2.rlh"  
